// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2021_1_DuckLuck/internal/pkg/notification (interfaces: Repository)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	models "github.com/go-park-mail-ru/2021_1_DuckLuck/internal/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddSubscribeUser mocks base method.
func (m *MockRepository) AddSubscribeUser(arg0 uint64, arg1 *models.Subscribes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSubscribeUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSubscribeUser indicates an expected call of AddSubscribeUser.
func (mr *MockRepositoryMockRecorder) AddSubscribeUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSubscribeUser", reflect.TypeOf((*MockRepository)(nil).AddSubscribeUser), arg0, arg1)
}

// DeleteSubscribeUser mocks base method.
func (m *MockRepository) DeleteSubscribeUser(arg0 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscribeUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscribeUser indicates an expected call of DeleteSubscribeUser.
func (mr *MockRepositoryMockRecorder) DeleteSubscribeUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscribeUser", reflect.TypeOf((*MockRepository)(nil).DeleteSubscribeUser), arg0)
}

// SelectCredentialsByUserId mocks base method.
func (m *MockRepository) SelectCredentialsByUserId(arg0 uint64) (*models.Subscribes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectCredentialsByUserId", arg0)
	ret0, _ := ret[0].(*models.Subscribes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectCredentialsByUserId indicates an expected call of SelectCredentialsByUserId.
func (mr *MockRepositoryMockRecorder) SelectCredentialsByUserId(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectCredentialsByUserId", reflect.TypeOf((*MockRepository)(nil).SelectCredentialsByUserId), arg0)
}
