// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2021_1_DuckLuck/internal/pkg/notification (interfaces: Handler)

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// GetNotificationPublicKey mocks base method.
func (m *MockHandler) GetNotificationPublicKey(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetNotificationPublicKey", arg0, arg1)
}

// GetNotificationPublicKey indicates an expected call of GetNotificationPublicKey.
func (mr *MockHandlerMockRecorder) GetNotificationPublicKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationPublicKey", reflect.TypeOf((*MockHandler)(nil).GetNotificationPublicKey), arg0, arg1)
}

// SubscribeUser mocks base method.
func (m *MockHandler) SubscribeUser(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SubscribeUser", arg0, arg1)
}

// SubscribeUser indicates an expected call of SubscribeUser.
func (mr *MockHandlerMockRecorder) SubscribeUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeUser", reflect.TypeOf((*MockHandler)(nil).SubscribeUser), arg0, arg1)
}

// UnsubscribeUser mocks base method.
func (m *MockHandler) UnsubscribeUser(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnsubscribeUser", arg0, arg1)
}

// UnsubscribeUser indicates an expected call of UnsubscribeUser.
func (mr *MockHandlerMockRecorder) UnsubscribeUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeUser", reflect.TypeOf((*MockHandler)(nil).UnsubscribeUser), arg0, arg1)
}
