// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2021_1_DuckLuck/internal/pkg/promo_code (interfaces: UseCase)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	models "github.com/go-park-mail-ru/2021_1_DuckLuck/internal/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// ApplyPromoCodeToOrder mocks base method.
func (m *MockUseCase) ApplyPromoCodeToOrder(arg0 *models.PromoCodeGroup) (*models.DiscountedPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyPromoCodeToOrder", arg0)
	ret0, _ := ret[0].(*models.DiscountedPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyPromoCodeToOrder indicates an expected call of ApplyPromoCodeToOrder.
func (mr *MockUseCaseMockRecorder) ApplyPromoCodeToOrder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyPromoCodeToOrder", reflect.TypeOf((*MockUseCase)(nil).ApplyPromoCodeToOrder), arg0)
}
