// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2021_1_DuckLuck/internal/pkg/promo_code (interfaces: Repository)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	models "github.com/go-park-mail-ru/2021_1_DuckLuck/internal/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CheckPromo mocks base method.
func (m *MockRepository) CheckPromo(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPromo", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckPromo indicates an expected call of CheckPromo.
func (mr *MockRepositoryMockRecorder) CheckPromo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPromo", reflect.TypeOf((*MockRepository)(nil).CheckPromo), arg0)
}

// GetDiscountPriceByPromo mocks base method.
func (m *MockRepository) GetDiscountPriceByPromo(arg0 uint64, arg1 string) (*models.PromoPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscountPriceByPromo", arg0, arg1)
	ret0, _ := ret[0].(*models.PromoPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscountPriceByPromo indicates an expected call of GetDiscountPriceByPromo.
func (mr *MockRepositoryMockRecorder) GetDiscountPriceByPromo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscountPriceByPromo", reflect.TypeOf((*MockRepository)(nil).GetDiscountPriceByPromo), arg0, arg1)
}
